name: Hello World!
description: Prints "Hello World!" when someone pushes to the main branch

on: 
  push: 
    branches: 
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          date
      - name: Directory content
        run: |
          ls -l