name: Deployment pipeline

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install
      - name: Check style
        run: pnpm run eslint
      - name: Run tests
        run: pnpm run test
      - name: Build project
        run: pnpm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: e2e tests
        run: pnpm run test:e2e
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
