name: Deployment pipeline

on: 
  push: 
    branches: 
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install
      - name: Check style
        run: pnpm run eslint
      - name: Run tests
        run: pnpm run test
      - name: Build project
        run: pnpm run build
      - name: Run end 2 end tests
        run: pnpm run test:e2e