name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SHOULD_SKIP: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install dependencies
        run: pnpm install

      - name: Check style
        run: pnpm run eslint

      - name: Run tests
        run: pnpm run test

      - name: Run e2e tests
        run: |
          npx playwright install --with-deps
          pnpm run test:e2e

      - name: Build project
        id: build
        run: pnpm run build

      - name: Build failure notification
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          details: Failed to build, latest commit - ${{ github.event.head_commit.id }}

      - name: Deploy project
        id: deploy
        if: ${{ github.event_name == 'push' && env.SHOULD_SKIP == false }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy success notification
        uses: rjstone/discord-webhook-notify@v2
        if: ${{ success() && steps.deploy.conclusion == 'success' }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          details: Deployment to Fly is successful

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && env.SHOULD_SKIP == false }}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
