name: Testing stuff
on:
  push:
    branches:
      - main
jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: should skip
        run: |
          echo ${{  github.event.commits.*.message }}
          echo ${{  contains(github.event.commits.*.message, '#skip') }}
      - name: secrets
        run: |
          echo ${{ secrets.DISCORD_WEBHOOK }}
          echo ${{ secrets.FLY_API_TOKEN }}
          echo ${{ secrets.GITHUB_TOKEN }}